CFLAGS = -g -Wall # -DDEBUG=1

all: tcpc tcps tcp2c tcp2s udpc udps

tcpc: tcpc.c

tcps: tcps.c

tcp2c: tcp2c.c

tcp2s: tcp2s.c

udpc: udpc.c

udps: udps.c

clean:
	rm -f *.o tcpc tcps tcp2c tcp2s udpc udps
